### ISSUE TITLE
Clean Codebase

### ISSUE THREAD

**Issue by henningkayser** [ros-planning/moveit2#102]
General (non-technical) cleanup steps and linting tools for better consistency in the code and maintainability.

## TODOs
- [x] ament_lint, clang-tidy-fix (#210)
- [ ] Unify logging, apply logger name conventions across codebase
- [ ] Use RCL_ROS_TIME where applicable
- [ ] Remove redundant meta packages
- [ ] Update documentation, cleanup ROS 1 references (i.e. NodeHandle, parameter server... )
- [ ] Remove commented and deprecated code, outdated TODO's

### Old description:

In order enforce clean coding standards using clang-format, clang-tidy (others?) we should enable ament-lint for all packages (https://github.com/ament/ament_lint).

Related/duplicate with #98. (https://ubuntu.com/blog/how-to-add-a-linter-to-ros-2)

**Comment by henningkayser** [comment]
Related to https://github.com/ros-planning/moveit2/pull/140:

* Unify logging (logger names, use of macros)
* Use rclcpp::Time and RCL_ROS_TIME where applicable
* Use `#include <...>`for rclcpp includes
* Remove now redundant meta packages
* Clean up CMakeLists files (remove obsolete dependencies, unify indentation, ament_lint)
* Update documentation/logging references to ROS 1 concepts (NodeHandle, parameter server, ...)
* Remove commented code or add issues linking to it where necessary

**Comment by henningkayser** [comment]
There are also a bunch of other linters that we can check for in CI or run with ament. I'm thinking of enabling `[ament_cpp_common](https://github.com/ament/ament_lint/blob/master/ament_lint_common/doc/index.rst)` at some point, but we probably want to maintain our own ruleset for this. The next ones to enable are imo:

* ament_cppcheck - only shows 11 errors in MoveIt for me
* ament_cpplint - shows 3618 errors with --linelength set to 120, but thiese include a lot of formatting issues (i.e. `else` should be in same line as `}`) and overall redundancy, so maybe we can get this enabled with our own rules while keeping the diff to MoveIt1 minimal
