### ISSUE TITLE
Hybrid Planning Feature

### ISSUE THREAD

**Issue by sjahr** [ros-planning/moveit2#433]
This issue tracks the current status of development for the new [hybrid planning feature for MoveIt 2](https://github.com/ros-planning/moveit2/tree/feature/hybrid_planning). After a basic version with a proof-of-concept demo was implemented last winter (#300), the current version of hybrid planning can be found on a [feature branch of MoveIt2](https://github.com/ros-planning/moveit2/tree/feature/hybrid_planning/moveit_ros/hybrid_planning). The next goal is to include the feature into the main version of MoveIt 2. The associated PR #488 is currently under review. Additionally, there is PR open,  which will add a [tutorial for the Hybrid Planning feature](https://github.com/sjahr/moveit2_tutorials/blob/add_hybrid_planning_tutorial/doc/hybrid_planning/hybrid_planning_tutorial.rst) and there is a [demo in progress ](https://github.com/PickNikRobotics/UR10e_welding_demo)that uses Hybrid Planning in a welding application. 

 - [X] Update use newest MoveIt 2 version and improvements: #426 
 - [ ] Create unit tests
 - [X] Refactor proof-of-concept plugins: #447 
 - [X] Improve documentation and a tutorial: [moveit2_tutorials #97](https://github.com/ros-planning/moveit2_tutorials/pull/97)
 - [x] Merge feature branch into main: #813 
 - [ ] Include more sophicticated algorithms into the hybrid planning pipeline
-  [x] Create a demo with real hardware: [UR10e_welding_demo](https://github.com/PickNikRobotics/UR10e_welding_demo)

Feel free to leave a comment if you have any ideas or questions!

**Comment by AndyZe** [comment]
This has all been done now!  :+1:
